### ISSUE TITLE
An Exception happened due to Parse error in symfony/translation/Translator.php ran with PHP < 7.1

### ISSUE THREAD

**Issue by mydansun** [briannesbitt/Carbon#1427]
Hi

When I set ```locale => zh-CN``` in config/app.php of Laravel. I will get an exception as follow.

```
[2018-08-27 18:42:20] local.ERROR: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) at /var/www/vendor/symfony/translation/Translator.php:79)
[stacktrace]
#0 /var/www/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/www/evermc...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Symfony\\\\Compone...')
#2 /var/www/vendor/nesbot/carbon/src/Carbon/Translator.php(7): spl_autoload_call('Symfony\\\\Compone...')
#3 /var/www/vendor/composer/ClassLoader.php(444): include('/var/www/evermc...')
#4 /var/www/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/www/evermc...')
#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Carbon\\\\Translat...')
#6 /var/www/vendor/nesbot/carbon/src/Carbon/Carbon.php(1624): spl_autoload_call('Carbon\\\\Translat...')
#7 /var/www/vendor/nesbot/carbon/src/Carbon/Carbon.php(1671): Carbon\\Carbon::translator()
#8 /var/www/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(29): Carbon\\Carbon::setLocale('zh-CN')
#9 /var/www/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(21): Carbon\\Laravel\\ServiceProvider->updateLocale()
#10 [internal function]: Carbon\\Laravel\\ServiceProvider->boot()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#14 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#15 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(Carbon\\Laravel\\ServiceProvider))
#17 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Carbon\\Laravel\\ServiceProvider), 17)
#18 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#20 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#21 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#22 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#23 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 {main}
"} 
```

Now, I have to use the following method to temporarily solve this problem.

Modify the composer.json to disable the auto-discover of Carbon package.
```json
"extra": {
        "laravel": {
            "dont-discover": [
                "nesbot/carbon"
            ]
        }
    },
```

**Comment by mydansun** [comment]
Thank you for help! This exception came from the queue and I think maybe the php-worker uses different version of PHP from my workspace. I will have a try later.
