### ISSUE TITLE
Maximum execution time of 60 seconds exceeded 

### ISSUE THREAD

**Issue by DepickereSven** [briannesbitt/Carbon#1848]
Hello,

I encountered an issue with the following code:
```php
                $timeDifference = $fromMainLineToGradeStationTo[$MGel]['arrivalTime']->diffInSeconds($fromGradeStationToDestination[$GDel]['departureTime'], false);

```
That is how `$fromMainLineToGradeStationTo` looks:
```
[
  {
         "departureTime": "2019-08-14T05:59:00.000000Z",
         "arrivalTime": "2019-08-14T06:47:00.000000Z"
    }
]

```

That is how `$fromMainLineToGradeStationTo` looks:
```
[
  {
        "departureTime": "2019-08-14T05:27:00.000000Z",
         "arrivalTime": "2019-08-14T06:43:00.000000Z"
    }
]

```

Carbon version: **2.22**

PHP version: **7.3.8**

I expected to get:

```
should give a timeDifference
```

But I actually get:

```
[2019-08-14 19:35:12] local.ERROR: Maximum execution time of 60 seconds exceeded {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 60 seconds exceeded at F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\
esbot\\carbon\\src\\Carbon\\CarbonInterval.php:221)
[stacktrace]
#0 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(148): Symfony\\Component\\Debug\\Exception\\FatalErrorException->__construct()
#1 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(134): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->fatalExceptionFromError()
#2 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(0): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#3 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\
esbot\\carbon\\src\\Carbon\\CarbonInterval.php(650): Carbon\\CarbonInterval->__construct()
#4 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\
esbot\\carbon\\src\\Carbon\\Traits\\Difference.php(87): Carbon\\CarbonInterval::instance()
#5 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\
esbot\\carbon\\src\\Carbon\\Traits\\Difference.php(330): Carbon\\Carbon::fixDiffInterval()
#6 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\app\\Http\\Controllers\\FilterFunctions\\Transfers\\MergeDifferentRouteLinesWithTransfers\\MergeDifferentTransfers.php(37): Carbon\\Carbon->diffInSeconds()
#7 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\app\\Http\\Controllers\\FilterFunctions\\Transfers\\MergeDifferentRouteLinesWithTransfers\\MergeDifferentTransfers.php(16): App\\Http\\Controllers\\FilterFunctions\\Transfers\\MergeDifferentRouteLinesWithTransfers\\MergeDifferentTransfers->mergeTheDifferentRoutesToOne()
#8 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\app\\Http\\Controllers\\FilterFunctions\\Transfers\\CreateMultipleRoutes\\CreateMultipleRoutesBasedOnLine.php(45): App\\Http\\Controllers\\FilterFunctions\\Transfers\\MergeDifferentRouteLinesWithTransfers\\MergeDifferentTransfers->getRouteMergedFromGradeStationToDestination()
#9 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\app\\Http\\Controllers\\FilterFunctions\\Transfers\\CreateMultipleRoutes\\CreateMultipleRoutesBasedOnLine.php(36): App\\Http\\Controllers\\FilterFunctions\\Transfers\\CreateMultipleRoutes\\CreateMultipleRoutesBasedOnLine->mergeRoutesDirectlyAndWithExtraStops()
#10 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\app\\Http\\Controllers\\FilterFunctions\\Transfers\\CreateMultipleRoutes\\CreateMultipleRoutesBasedOnLine.php(15): App\\Http\\Controllers\\FilterFunctions\\Transfers\\CreateMultipleRoutes\\CreateMultipleRoutesBasedOnLine->getRoutesFromRoundLineToOtherLine()
#11 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\app\\Http\\Controllers\\FilterFunctions\\Transfers\\FilterForTransfersInsteadOfDirectLinesBecauseTheMainRouteCodeIsntCorrect.php(34): App\\Http\\Controllers\\FilterFunctions\\Transfers\\CreateMultipleRoutes\\CreateMultipleRoutesBasedOnLine->determineTheRoutes()
#12 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\app\\Http\\Controllers\\FilterFunctions\\FilterRoutesCodes.php(41): App\\Http\\Controllers\\FilterFunctions\\Transfers\\FilterForTransfersInsteadOfDirectLinesBecauseTheMainRouteCodeIsntCorrect->determineStartAndStopPositions()
#13 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\app\\Http\\Controllers\\MainController.php(28): App\\Http\\Controllers\\FilterFunctions\\FilterRoutesCodes->filterTheNotCorrectRoutesOut()
#14 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\MainController->getAllRoutesOfACertainDay()
#15 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array:{F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php:54}()
#16 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): App\\Http\\Controllers\\MainController->callAction()
#17 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#18 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#19 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(680): Illuminate\\Routing\\Route->run()
#20 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php:678-682}()
#21 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php:28-36}()
#22 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#23 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:140-169}()
#24 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php:47-59}()
#25 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#26 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:140-169}()
#27 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php:47-59}()
#28 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Routing\\Pipeline->then()
#29 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack()
#30 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute()
#31 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute()
#32 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#33 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): App\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php:173-177}()
#34 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php:28-36}()
#35 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#36 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:140-169}()
#37 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php:47-59}()
#38 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): App\\Http\\Middleware\\TrimStrings->handle()
#39 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:140-169}()
#40 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php:47-59}()
#41 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#42 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:140-169}()
#43 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php:47-59}()
#44 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): App\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#45 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:140-169}()
#46 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php:47-59}()
#47 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): App\\Http\\Middleware\\TrustProxies->handle()
#48 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:140-169}()
#49 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure:F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php:47-59}()
#50 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Routing\\Pipeline->then()
#51 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): App\\Http\\Kernel->sendRequestThroughRouter()
#52 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\public\\index.php(55): App\\Http\\Kernel->handle()
#53 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\server.php(21): ()
#54 F:\\Dev\\TRA\\BackendPHP\\TraBackendLogic\\TRA-app-backend\\server.php(0): {main}()
#55 {main}
"} 
```

Thanks!

**Comment by kylekatarnls** [comment]
Thanks for the report, I will inspect that.

**Comment by DepickereSven** [comment]
It was my fault I created by accident a never-ending loop

**Comment by kylekatarnls** [comment]
Oh great, I was just about to start the inspection. Thanks for the feedback.
