### ISSUE TITLE
BUG: Error with Laravel Octane + RoadRunner

### ISSUE THREAD

**Issue by ahkui** [briannesbitt/Carbon#2773]
Hello,

I encountered an issue with the following exception:
```
Uncaught Error: Call to undefined method Illuminate\\Support\\Facades\\Config::get() in /var/www/current/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1261
Stack trace:
#0 /var/www/current/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(104): Illuminate\\Foundation\\Application->getLocale()
#1 /var/www/current/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(63): Carbon\\Laravel\\ServiceProvider->getLocale()
#2 /var/www/current/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(56): Carbon\\Laravel\\ServiceProvider->updateLocale()
#3 /var/www/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Carbon\\Laravel\\ServiceProvider->Carbon\\Laravel\\{closure}(Object(Illuminate\\Foundation\\Events\\LocaleUpdated))
#4 /var/www/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Foun...', Array)
#5 /var/www/current/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1296): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Foun...')
#6 /var/www/current/app/Exceptions/ApiException.php(40): Illuminate\\Foundation\\Application->setLocale(NULL)
#7 /var/www/current/app/Exceptions/Handler.php(128): App\\Exceptions\\ApiException->render(Object(Illuminate\\Http\\Request))
#8 /var/www/current/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(439): App\\Exceptions\\Handler->App\\Exceptions\\{closure}(Object(Spiral\\Goridge\\Exception\\HeaderException), Object(Illuminate\\Http\\Request))
#9 /var/www/current/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(369): Illuminate\\Foundation\\Exceptions\\Handler->renderViaCallbacks(Object(Illuminate\\Http\\Request), Object(Spiral\\Goridge\\Exception\\HeaderException))
#10 /var/www/current/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Spiral\\Goridge\\Exception\\HeaderException))
#11 /var/www/current/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Spiral\\Goridge\\Exception\\HeaderException))
#12 /var/www/current/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Spiral\\Goridge\\Exception\\HeaderException))
#13 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(Object(Spiral\\Goridge\\Exception\\HeaderException))
```

PHP version: 8.1.4

laravel/octane#664
#2638 

Thanks!

**Comment by kylekatarnls** [comment]
Hello, this is not a bug in Carbon. At this point of time, we see that `Illuminate\\Foundation\\Application->getLocale` exists and we just call it.

`vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1261` is Laravel code, and it's up to octane to ensure the needed facades (such as `Illuminate\\Support\\Facades\\Config::get()`) are loaded when they are loaded from Laravel methods.

Side note: if you don't have dates to be displayed translated or formatted according to the current locale, then you can disabled this service provider using [dont-discover](https://laravel.com/docs/10.x/packages#opting-out-of-package-discovery)

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "nesbot/carbon"
        ]
    }
},
```

**Comment by ahkui** [comment]
Got it, thanks.
