### ISSUE TITLE
Cannot validate invalid date/time

### ISSUE THREAD

**Issue by trymeouteh** [briannesbitt/Carbon#2785]
Hello,

I encountered an issue with the following code:

```
<?php

require_once('vendor/autoload.php');

use Carbon\Carbon;



$dateTime = Carbon::parse('2020-13-09T15:04:08.007');

if ($dateTime->isValid()) {
    echo 'Valid';
};
```

Carbon version: 2.66

PHP version: 8.1.12

I expected to get:

Working PHP script with no errors.

```
6
```

But I actually get:

```
Fatal error: Uncaught Exception: Failed to parse time string (2020-13-09T15:04:08.007) at position 6 (3): Unexpected character in /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:87 Stack trace: #0 /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(87): DateTime->__construct('2020-13-09T15:0...', Object(Carbon\CarbonTimeZone)) #1 /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(185): Carbon\Carbon->__construct('2020-13-09T15:0...', NULL) #2 /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(216): Carbon\Carbon::rawParse('2020-13-09T15:0...', NULL) #3 /opt/lampp/htdocs/carbon/Validation.php(9): Carbon\Carbon::parse('2020-13-09T15:0...') #4 {main} Next Carbon\Exceptions\InvalidFormatException: Failed to parse time string (2020-13-09T15:04:08.007) at position 6 (3): Unexpected character in /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:89 Stack trace: #0 /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(185): Carbon\Carbon->__construct('2020-13-09T15:0...', NULL) #1 /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(216): Carbon\Carbon::rawParse('2020-13-09T15:0...', NULL) #2 /opt/lampp/htdocs/carbon/Validation.php(9): Carbon\Carbon::parse('2020-13-09T15:0...') #3 {main} Next Carbon\Exceptions\InvalidFormatException: Could not parse '2020-13-09T15:04:08.007': Failed to parse time string (2020-13-09T15:04:08.007) at position 6 (3): Unexpected character in /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:190 Stack trace: #0 /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(216): Carbon\Carbon::rawParse('2020-13-09T15:0...', NULL) #1 /opt/lampp/htdocs/carbon/Validation.php(9): Carbon\Carbon::parse('2020-13-09T15:0...') #2 {main} thrown in /opt/lampp/htdocs/carbon/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 190
```

**Comment by kylekatarnls** [comment]
Hello,

`Carbon` extends `DateTime` and this error comes from `DateTime` itself.

I believe it's way safer to let this error occur rather than swaloing it and require devs to explicitly call `->isValid()` to check errors.

Also it's fairly simple to just catch the exception on your side:

```php
try {
    $dateTime = Carbon::parse('2020-13-09T15:04:08.007');
} catch (\Throwable) {
    $dateTime = null;
}

if ($dateTime?->isValid()) {
    echo 'Valid';
} else {
    echo 'invalid';
}
```

You can read this thread for other possible work-arounds: #450

**Comment by trymeouteh** [comment]
> 

This works, but what does the question mark mean in `$dateTime?->isValid() `

Never seen this before in PHP
