### ISSUE TITLE
Unable to add unit array error since updating to v3

### ISSUE THREAD

**Issue by sts-ryan-holton** [briannesbitt/Carbon#2976]
Hello,

I encountered an issue with the following code within my recently upgraded Laravel 11 project that was previously using the latest version of Carbon PHP v2, now, using the latest of v3 I'm experiencing an intermittent problem with some code

```php
/**
 * Get charts
 */
protected function getCharts($monitor, $period = 24, $mode = 'average', $device = 'desktop')
{
    // user
    $user = Auth::user();

    /*
    * NOTE: the reason we do addHours($diff) is so that we don't miss
    * any data available to a user, in reality this hour difference could
    * be less, such as 12 hours.
    */

    // get UK time since that's the time data is saved
    $nowUK = Carbon::now();

    // get the user's local time, in their timezone
    $nowLocal = Carbon::now()->setTimezone($user->timezone)->toDateTimeString();

    // calculate the difference in hours so we can ensure a 24 hours period of data
    $diff = $nowUK->diffInHours($nowLocal);

    $from = Carbon::now()->setTimezone($user->timezone)->subHours($period)->toDateTimeString();
    $to = Carbon::now()->setTimezone($user->timezone)->addHours($diff)->toDateTimeString();

    $checkDateFormat = $period > 48 ? '%Y-%m-%d' : '%Y-%m-%d %H:00:00';
    $model = $period > 48 ? UptimeDailySummaryStat::class : UptimeHourlySummaryStat::class;

    // get the response times for past X hours
    $responseTimes = $model::where('user_id', Auth::id())
        ->where('monitor_id', $monitor['id'])
        ->where('grouped_at', '>=', $from)
        ->where('grouped_at', '<=', $to)
        ->select(
            DB::raw('SUM(total_checks_performed) AS total_events'),
            DB::raw('SUM(total_successful_checks_performed) AS up_events'),
            DB::raw('SUM(avg_response_duration) AS response_time'),
            DB::raw("DATE_FORMAT(grouped_at, '$checkDateFormat') AS group_date"),
        )
        ->groupBy('group_date')
        ->orderBy('group_date', 'asc')
        ->get();

    if (! $responseTimes) {
        return [];
    }

    $timeline = $this->getUptimeTimeline($monitor['id'], $responseTimes, $from, $to, $device, $period, $user);

    if (! $timeline) {
        return [];
    }

    $charts = [
        'uptime' => $timeline,
        'response' => [
            'labels' => [],
            'data' => [],
        ],
    ];

    foreach ($responseTimes as $uptime) {
        array_push($charts['response']['labels'], Carbon::parse($uptime['group_date'])->setTimezone($user->timezone)->toISOString());
        array_push($charts['response']['data'], intval($uptime['response_time']));
    }

    return $charts;
}
```

Carbon version: **3.1.1**

PHP version: **8.3.4**

I expected to get:

Ideally not an error since coming from v2 there's no issue and i can't find an upgrade guide for carbon v3

But I actually get:

```
[2024-03-25 11:57:59] local.ERROR: Unable to add unit array (
  0 => 'hour',
  1 => -3.08025E-5,
  2 => NULL,
) {"userId":142,"exception":"[object] (Carbon\\Exceptions\\UnitException(code: 0): Unable to add unit array (
  0 => 'hour',
  1 => -3.08025E-5,
  2 => NULL,
) at /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Units.php:336)
[stacktrace]
#0 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Date.php(2698): Carbon\\Carbon->addUnit()
#1 /var/www/html/app/Http/Controllers/Account/MonitorController.php(109): Carbon\\Carbon->__call()
#2 /var/www/html/app/Http/Controllers/Account/MonitorController.php(590): App\\Http\\Controllers\\Account\\MonitorController->getCharts()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Account\\MonitorController->show()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\\Routing\\Route->runController()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#9 /var/www/html/app/Http/Middleware/ValidateAccountOwningModel.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ValidateAccountOwningModel->handle()
#11 /var/www/html/app/Http/Middleware/OnboardingJourney.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\OnboardingJourney->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\EnsureEmailIsVerified->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(159): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(90): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(64): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#22 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#24 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/AuthenticateSession.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\\Sanctum\\Http\\Middleware\\AuthenticateSession->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, it's difficult to see what's the issue since I don't know what line matches the `109` of your `MonitorController.php` file.

Can you make a minimum code sample free of DB/application context so that I can run it as is on my side and reproduce your error?

**Comment by sts-ryan-holton** [comment]
Line 109 is:

```php
$to = Carbon::now()->setTimezone($user->timezone)->addHours($diff)->toDateTimeString();
```

I figured it might be something to do with the breaking change to how `diffIn*` methods work. So I've wrapped these in the `(int)` checks

**Comment by fulopattila122** [comment]
**The content I've added here is entirely informational. It may help others. No need to reopen the issue.**

I stumbled upon this problem, and here's the code causing this after v2 -> v3 upgrade:

```php
    function timeDiffInEnglish(Carbon $date): string
    {
        $hours = $date->diffInHours();
        $minutes = match ($hours) {
            0 => $date->diffInMinutes(),
            default => $date->copy()->addHours($hours)->diffInMinutes(),
        };

        $result = 0 !== $hours ? sprintf('%d hours and ', $hours) : '';
        $result .= sprintf('%d minutes ago', $minutes);

        return $result . ' at {' . $date->toAtomString() . '}';
    }
```

Running it consecutively several times within a second causes it sometimes to pass, sometimes to fail:

<img width="1476" height="1344" alt="Image" src="https://github.com/user-attachments/assets/d3519b25-7404-4021-a604-a78494ad5bb9" />

**Comment by kylekatarnls** [comment]
Hi, [diffIn* methods are now returning float number](https://carbon.nesbot.com/guide/getting-started/migration.html#diffin), you would need to cast it to int to match v2 behavior:
```php
    function timeDiffInEnglish(Carbon $date): string
    {
        $hours = (int) abs($date->diffInHours());
        $minutes = (int) abs(match ($hours) {
            0 => $date->diffInMinutes(),
            default => $date->copy()->addHours($hours)->diffInMinutes(),
        });

        $result = 0 !== $hours ? sprintf('%d hours and ', $hours) : '';
        $result .= sprintf('%d minutes ago', $minutes);

        return $result . ' at {' . $date->toAtomString() . '}';
    }
```

**Comment by kylekatarnls** [comment]
For the particular snippet above though, I rather suggest:

```php
    function timeDiffInEnglish(Carbon $date): string
    {
        $minutes = (int) abs($date->diffInMinutes());
        $hours = (int) ($minutes / 60);
        $minutes %= 60;

        $result = 0 !== $hours ? sprintf('%d hours and ', $hours) : '';
        $result .= sprintf('%d minutes ago', $minutes);

        return $result . ' at {' . $date->toAtomString() . '}';
    }
```

**Comment by fulopattila122** [comment]
Yep, I understand that part, and I even fixed it myself.

What I don't understand is how the diff becomes an array.

Anyway, I don't want to rob your time. My aim was to provide sample code that reproduces the given error, since the op didn't include any.

**Comment by kylekatarnls** [comment]
`addHours(3)` is a magic method, it's handled by `__call('addHours', [3])`, which will in turn call `addUnit('hours', 3, null)` so the `array` you see there (`['hours', 3, null]`) is what get passed as a list of arguments in the end to `addUnit`.

**Comment by kylekatarnls** [comment]
On the top of that the "adding" will call `->modify("3 hours")` it works fine with number that can be represented without scientist notation, but with very small number, casting it to string and passing it to `modify` fails.

This is another bug that will be solved in the next version https://github.com/CarbonPHP/carbon/pull/105

**Comment by fulopattila122** [comment]
Thanks for the explanation! 🙇
